name: Vite CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 檢出專案程式碼
      - name: Checkout Code
        uses: actions/checkout@v3

      # 設定 Node.js 環境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 安裝依賴套件
      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      # 執行測試
      - name: Run Tests
        run: npm run test:unit

      - name: Run E2E Tests # 執行端對端測試
        run: npm run test:e2e # 執行 E2E 測試腳本，模擬用戶行為並驗證應用是否正確

      # 編譯建置專案
      - name: Build Project
        run: npm run build

      # 部署到 GitHub Pages（如果需要部署）
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist
